# Generated by Django 4.1.3 on 2022-11-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('edad', models.SmallIntegerField()),
            ],
        ),
    ]
